local ReAct = require("avante.libs.ReAct_parser2")

describe("ReAct_parser2", function()
  it("parses fenced json tool calls", function()
    local res = ReAct.parse('```json\n{"name": "str_replace", "input": {"path": "src/main.ts"}}\n```')
    assert.are.same(1, #res)
    assert.are.same("tool_use", res[1].type)
    assert.are.same("str_replace", res[1].tool_name)
    assert.is_false(res[1].partial)
  end)

  it("parses fenced json tool calls with the name field last", function()
    local res = ReAct.parse('```json\n{"input": {"path": "src/main.ts"}, "name": "str_replace"}\n```')
    assert.are.same(1, #res)
    assert.are.same("tool_use", res[1].type)
    assert.are.same("str_replace", res[1].tool_name)
    assert.is_false(res[1].partial)
  end)

  it("parses unclosed fenced json as a partial tool use", function()
    local res = ReAct.parse('```json\n{"name": "str_replace", "input": {"path": "src/ma')
    assert.are.same(1, #res)
    assert.are.same("tool_use", res[1].type)
    assert.are.same("str_replace", res[1].tool_name)
    assert.is_true(res[1].partial)
  end)

  it("keeps non-tool fenced json as text", function()
    local res = ReAct.parse('```json\n{"a": 1}\n```')
    assert.are.same(1, #res)
    assert.are.same("text", res[1].type)
  end)

  it("still parses xml tool_use blocks", function()
    local res = ReAct.parse('<tool_use>\n{"name": "glob", "input": {"path": "src"}}\n</tool_use>')
    assert.are.same(1, #res)
    assert.are.same("tool_use", res[1].type)
    assert.are.same("glob", res[1].tool_name)
    assert.is_false(res[1].partial)
  end)
end)
