name: 🐛 Bug Report
description: Create a bug report to help us improve Avante
title: 'bug: '
labels: ['bug']
body:
  - type: markdown
    id: issue-already-exists
    attributes:
      value: |
        Please search to see if an issue already exists for the bug you encountered.
        See [Searching Issues and Pull Requests](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests) for how to use the GitHub search bar and filters.
  - type: textarea
    id: describe-the-bug
    validations:
      required: true
    attributes:
      label: Describe the bug
      description: Please provide a clear and concise description about the problem you ran into.
      placeholder: This happened when I ...
  - type: textarea
    id: to-reproduce
    validations:
      required: false
    attributes:
      label: To reproduce
      description: |
        Please provide a code sample or a code snippet to reproduce said problem. If you have code snippets, error messages, or a stack trace please also provide them here.

        **IMPORTANT**: make sure to use [code tags](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#syntax-highlighting) to correctly format your code. Screenshots are helpful but don't use them for code snippets as they don't allow others to copy-and-paste your code.

      placeholder: |
        Give a minimal config to reproduce the issue.
  - type: textarea
    id: expected-behavior
    validations:
      required: false
    attributes:
      label: Expected behavior
      description: 'A clear and concise description of what you would expect to happen.'
  - type: textarea
    id: how-to-install
    validations:
      required: true
    attributes:
      label: Installation method
      description: |
        Please share your installation method with us.
      value: |
        Use lazy.nvim:
        ```lua
        {
          "yetone/avante.nvim",
          event = "VeryLazy",
          lazy = false,
          version = false, -- set this if you want to always pull the latest change
          opts = {
            -- add any opts here
          },
          -- if you want to build from source then do `make BUILD_FROM_SOURCE=true`
          build = "make",
          -- build = "powershell -ExecutionPolicy Bypass -File Build.ps1 -BuildFromSource false" -- for windows
          dependencies = {
            "nvim-treesitter/nvim-treesitter",
            "stevearc/dressing.nvim",
            "nvim-lua/plenary.nvim",
            "MunifTanjim/nui.nvim",
          },
        }
        ```
  - type: textarea
    id: environment-info
    attributes:
      label: Environment
      description: |
        Please share your environment with us, including your neovim version using `nvim -v` and `uname -a`.
      placeholder: |
        neovim version: ...
        distribution (if any): ...
        platform: ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: Repro
      description: Minimal `init.lua` to reproduce this issue. Save as `repro.lua` and run with `nvim -u repro.lua`
      value: |
        vim.env.LAZY_STDPATH = ".repro"
        load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

        require("lazy.minit").repro({
          spec = {
            -- add any other plugins here
          },
        })
      render: lua
    validations:
      required: false
