name: Release

on:
  push:
    branches: ["release-v*"]
    tags: ["v*"]

permissions:
  contents: write
  packages: write

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      release_tag: ${{ steps.get_version.outputs.version }}
      release_body: "${{ steps.tag.outputs.message }}"

    steps:
      - uses: actions/checkout@v7

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@d97fbc34ceb64d1f5d95f4dfd6dce33521ccccf5 # ratchet:battila7/get-version-action@v2

      - name: Create Release
        id: create-release
        uses: ncipollo/release-action@v1
        with:
          draft: true
          name: "avante-libs ${{ steps.get_version.outputs.version }}"
          tag: ${{ steps.get_version.outputs.version }}
          generateReleaseNotes: true

  releases-matrix:
    needs: [create-release]
    strategy:
      fail-fast: false
      matrix:
        feature: [lua51, luajit]
        config:
          - os: ubuntu-24.04-arm
            os_name: linux
            arch: aarch64
            rust_target: aarch64-unknown-linux-gnu
            docker_platform: linux/aarch64
            container: quay.io/pypa/manylinux2014_aarch64
          - os: ubuntu-latest
            os_name: linux
            arch: x86_64
            rust_target: x86_64-unknown-linux-gnu
            docker_platform: linux/amd64
            container: quay.io/pypa/manylinux2014_x86_64 # for glibc 2.17
          - os: macos-latest
            os_name: darwin
            arch: x86_64
            rust_target: x86_64-apple-darwin
          - os: macos-latest
            os_name: darwin
            arch: aarch64
            rust_target: aarch64-apple-darwin
          - os: windows-latest
            os_name: windows
            arch: x86_64
            rust_target: x86_64-pc-windows-msvc
          - os: windows-latest
            os_name: windows
            arch: aarch64
            rust_target: aarch64-pc-windows-msvc

    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: ./.github/workflows/build.yaml
        with: ${{ matrix.config }}

      - name: Upload Release Asset
        if: ${{ matrix.config.os_name != 'windows' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ needs.create-release.outputs.release_tag }}" \
            "./results/avante_lib-${{ matrix.config.os_name }}-${{ matrix.config.arch }}-${{ matrix.feature }}.tar.gz" \
            --clobber

      - name: Upload Release Asset (Windows)
        if: ${{ matrix.config.os_name == 'windows' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload "${{ needs.create-release.outputs.release_tag }}" \
            "./results/avante_lib-${{ matrix.config.os_name }}-${{ matrix.config.arch }}-${{ matrix.feature }}.zip" \
            --clobber

  publish-release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    needs: [create-release, releases-matrix]

    steps:
      - name: publish release
        id: publish-release
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # ratchet:actions/github-script@v6
        env:
          release_id: ${{ needs.create-release.outputs.release_id }}
        with:
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: process.env.release_id,
              draft: false,
              prerelease: false
            })
