name: Rust CI

on:
  push:
    branches:
      - main
    paths:
      - "crates/**/*"
      - "Cargo.lock"
      - "Cargo.toml"
  pull_request:
    branches:
      - main
    paths:
      - "crates/**/*"
      - "Cargo.lock"
      - "Cargo.toml"

jobs:
  tests:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v7
      - uses: Swatinem/rust-cache@6323deb102c322ba6fcbdcafc7e3dddab59af2b6 # ratchet:Swatinem/rust-cache@v2
      # should match the flake toolchain
      - uses: dtolnay/rust-toolchain@52699249a776424c51ebc9ee197baf0f9dbf0d8a # ratchet:dtolnay/rust-toolchain@1.86
        with:
          toolchain: stable
          components: clippy, rustfmt
      - name: Run rust tests
        run: make rusttest
